name: CI

on:
  push:
    branches:
    - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Semantic release
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.UPM }}
          
    - name: update upm branch
      run: |
        echo '### head info'
        git log -1
        echo '### split upm branch'
        git subtree split -P "$PKG_ROOT" -b upm
        echo '### update remote upm branch'
        git push -f -u origin upm
      env:
        PKG_ROOT: Assets/Test
        
    - name: Create upm git tag
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git tag $TAG upm
        git push origin --tags
      env:
        TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
